gtree_build: gtree_build.cpp
	g++ -std=c++0x -O2 gtree_build.cpp -L/usr/local/lib/ -lmetis -o gtree_build
gtree_query: gtree_query.cpp
	g++ -std=c++0x -O2 gtree_query.cpp -L/usr/local/lib/ -lmetis -o gtree_query
