object:
	g++ object.cpp -o object
silc:
	g++ silc.cpp -o silc
query:
	g++ query_location.cpp -o query
knn: silc_knn.cpp
	g++ -o knn silc_knn.cpp
clean:
	rm silc; rm object; rm query; rm knn;
